name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Gradle 8.6
      run: |
        wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
        unzip -d /opt/gradle gradle-8.6-bin.zip
        echo "/opt/gradle/gradle-8.6/bin" >> $GITHUB_PATH

    - name: Build with Gradle
      run: gradle build --no-daemon
